repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9
    hooks:
      - id: ruff
        # 自动修复 Ruff 发现的问题
        args: [--fix]
      - id: ruff-format 
        # 自动格式化代码
        args: [--line-length, 120]
